### ISSUE TITLE
Evaluate possibility to use a different display module

### ISSUE THREAD

**Issue by AleCo3lho** [karnadii/sharp_memory_display_breakout#4]
Hey @karnadii, do you think it is possible to create a board that uses this display instead, it is much cheaper and would be an interesting option. https://aliexpress.com/item/1005005883553891.html

I am interesting in learning how to create such a product, let me know if I can help with anything.

**Comment by karnadii** [comment]
That is a different kind of display. You have to make a new pcb design. For e-paper refer to this repo by nicell https://github.com/Nicell/epaper-102
E-paper is energy efficient but not as fast as a sharp memory display though.

**Comment by AleCo3lho** [comment]
Hey, thank you for the fast response, you are amazing. 

I am from Brazil and the memory display ended up being to much expensive to import from nicell and to build it myself, even though e-paper is not good as memory display I think it is a good trade off in terms of energy efficiency. 

Specially when the only option we have is the OLED

**Comment by karnadii** [comment]
In that case, you can build the e-paper by nicell I linked above. All the material is in the readme. Or you can re create the pcb to use different e-paper sizes. For the firmware I don't know if it is officially supported in ZMK but some keyboard like corneish zen use e-paper as well. You can look into their firmware if you decide to build one. But take note, it will need more pinout and most keyboard is not compatible, so you need to design your keyboard as well to support e-paper.
